service: ares
runtime: python37

handlers:
- url: /app/static
  static_dir: static_cdn/

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10
