"""
Django settings for ares project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if sys.version_info.major > 2:
    from configparser import RawConfigParser
else:
    from ConfigParser import RawConfigParser

config = RawConfigParser()

if os.getenv('GAE_APPLICATION', None):
    config.read(os.path.join(BASE_DIR, "ares/prod.ini"))
    DATABASES = {
        'default': {
            'ENGINE': config.get('database', 'ENGINE'),
            'NAME': config.get('database', 'NAME'),
            'USER': config.get('database', 'USER'),
            'PASSWORD': config.get('database', 'PASSWORD'),
            'HOST': config.get('database', 'HOST'),
        }
    }
else:
    config.read(os.path.join(BASE_DIR, "ares/dev.ini"))
    DATABASES = {
        'default': {
            'ENGINE': config.get('database', 'ENGINE'),
            'NAME': config.get('database', 'NAME'),
            'USER': config.get('database', 'USER'),
            'PASSWORD': config.get('database', 'PASSWORD'),
            'HOST': config.get('database', 'HOST'),
            'PORT': config.get('database', 'PORT'),
        }
    }

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+@x48vv-m!lmj$n$(zt-6%ww$*)krva5y(fb1050y6d1wh33)0'
PAGE_INDEX = 0

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = ['*']

DEBUG = config.getboolean('debug', 'DEBUG')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ares.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "app", "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ares.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static_cdn")
MEDIA_ROOT = os.path.join(BASE_DIR, "media_cdn")
